# Generated by Django 3.0.8 on 2020-07-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sido', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('medical', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
            ],
        ),
    ]
